[package]
name = "kia_obd2_esp32c3_v2"
version = "0.1.0"
authors = ["dragonn <dragonn@op.pl>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Base ESP deps
esp32c3-hal = { version = "0.12.0", features = [
    "async",
    "embassy",
    "embassy-time-systick",
] }
esp-backtrace = { version = "0.8.0", features = [
    "esp32c3",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { version = "0.6.0", features = ["esp32c3"] }
esp-alloc = { version = "0.3.0" }

static_cell = { version = "1.2.0", features = ["nightly"] }

# Embassy deps
embassy-executor = { version = "0.3.0", features = [
    "nightly",
    "integrated-timers",
    "arch-riscv32",
    "executor-thread",
] }
embassy-time = { version = "0.1.3", features = ["nightly"] }


# OLED SSD1306 deps
sh1122 = { path = "./sh1122" }
embedded-graphics = "0.8.0"
tinybmp = "0.5.0"
embedded-text = "0.6.0"

display-interface = { git = "https://github.com/therealprof/display-interface", version = "0.5.0-alpha.1" }
display-interface-spi = { git = "https://github.com/therealprof/display-interface", version = "0.5.0-alpha.1", features = [
    "async",
    "nightly",
] }
inverted-pin = "0.2.0"
profont = "0.7.0"
