import { BatteryWidget } from "battery.slint";
import { EnergyFlow } from "energy-flow.slint";
import { MotorsWidget } from "motors.slint";
import { TemperatureWidget } from "temperature.slint";
import { DrivingDashboard } from "driving/mod.slint";
import { BottomBar } from "bottom-bar/mod.slint";
import { CoolantGauge } from "coolant.slint";

export component AppWindow inherits Window {
    height: 262px;
    width: 928px;

    title: "OBD2 Dashboard";
    in-out property <int> counter: 42;
    callback request-increase-value();
    in-out property <float> speed-kmh: 74;
    in-out property <float> clutch-temperature: 60;
    in-out property <float> clutch-temperature-deviation: 2;
    in-out property <int> gear: 3;
    in-out property <string> gear-mode: "D";
    in-out property <float> fuel-consumption: 4.8;
    in-out property <float> battery-power-kw: -2;
    in-out property <float> coolant-temperature: 88;

    background: #000000;

    BottomBar {
        x: 13px; y: parent.height - 57px;
        width: parent.width - 26px; height: 49px;
    }

    DrivingDashboard {
        x: 383px;
        y: 13px;
        width: 208px;
        height: 178px;
        speed-kmh: root.speed-kmh;
        clutch-temperature: root.clutch-temperature;
        clutch-temperature-deviation: root.clutch-temperature-deviation;
        gear: root.gear;
        gear-mode: root.gear-mode;
        fuel-consumption: root.fuel-consumption;
    }

    BatteryWidget {
        x: 5px;
        // Center the terminal on the energy-flow arrows at y = 106px.
        y: 34px;
        width: 249px;
        height: 144px;

        state-of-charge: 76;
        pack-voltage: 357.2;
        average-cell-voltage: 3.82;
        cell-voltage-deviation: 20;
        minimum-temperature: 18;
        maximum-temperature: 24;
    }

    EnergyFlow {
        x: 269px;
        y: 37px;
        width: 106px;
        height: 106px;
        power-kw: root.battery-power-kw;
        maximum-power-kw: 40;
    }

    CoolantGauge {
        x: 608px; y: 133px;
        width: 180px; height: 60px;
        temperature: root.coolant-temperature;
    }

    /*MotorsWidget {
        x: 464px;
        y: 16px;
        width: 190px;
        height: parent.height / 2 - 32px;
        ice-on: false;
        electric-on: true;
    }

    TemperatureWidget {
        x: 670px;
        y: 16px;
        width: 118px;
        height: parent.height / 2 - 32px;
        temperature: 100;
        minimum-temperature: 0;
        maximum-temperature: 130;
        label: "COOLANT";
    }*/
}
