[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"

eframe = "0.31.1"
egui = "0.31.1"

remoc = "0.15.3"
tokio = { version = "1.44.2", features = ["full"] }
