
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
max_width = 120
array_width = 120
attr_fn_like_width = 120
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
format_brace_macros = true
format_macro_bodies = true