[target.riscv32imc-unknown-none-elf]
#runner = "espflash flash --monitor -p /dev/ttyUSB1 -L defmt"
#runner = "probe-rs run --chip esp32c3 --connect-under-reset"
runner = ".cargo/run.sh"
[build]
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
    "-C",
    "force-frame-pointers",
    "-C",
    "link-arg=-Tdefmt.x",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]

[env]
DEFMT_LOG = "debug"
DEFMT_RTT_BUFFER_SIZE = "4096"
