[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF9160_xxAA"


[build]
target = "thumbv8m.base-none-eabi"

[env]
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "2048"
