[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip nRF9160_xxAA"
runner = "./.cargo/run.sh"

[build]
target = "thumbv8m.main-none-eabihf"
rustflags = []

[env]
DEFMT_LOG = "info"
DEFMT_RTT_BUFFER_SIZE = "512"

[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
