[env]
DEFMT_LOG = "info"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER = "/usr/bin/x86_64-linux-gnu-gcc"

[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C",
    "link-arg=-T/usr/lib/ldscripts/elf_x86_64.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "relocation-model=static",
    "-C",
    "target-feature=+crt-static",
]
#linker = "/usr/bin/clang"
