services:
  lyra-sdk:
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    image: luckfox-lyra-sdk:ubuntu-22.04
    working_dir: /sdk
    stdin_open: true
    tty: true
    volumes:
      - ./sdk:/sdk
      - ./kernel:/project/kernel:ro
      - ./buildroot:/project/buildroot:ro
      - ./device:/project/device:ro
      - ../obd2-dashboard-slint:/project/obd2-dashboard-slint:ro
      - ./patches:/project/patches:ro
